- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- cli/cmd/root.go
- cli/cmd/run.go
- cli/main.go
- internal/compose/convert.go
- internal/compose/convert_test.go
- internal/compose/types.go
- internal/compose/write.go
- internal/compose/write_test.go
- internal/version/version.go
Signed-off-by: rachfop <prachford@icloud.com>
> Adding Code of Conduct and Contributing docs

- .github/workflows/release.yaml
- cli/cmd/run.go
- internal/compose/convert.go
Sort output arrays and .env file contents.
> Sort output arrays and .env file contents

- compose.yaml
- internal/command/root.go
- internal/command/root_test.go
- internal/command/run.go
- internal/command/run_test.go
- internal/compose/convert.go
- internal/logging/logging.go
Duplicate of https://github.com/score-spec/score-compose/pull/55 to merge into #54 by mistake. This was previously approved by @delca85
> fix: reject unsupported features and log ignored ones

- internal/command/init.go
- internal/command/init_test.go
Fixes #98 , this ensures that a CI/CD system that may be using score can intentionally disable the default generation and run the following in an existing project:
```
score-compose init --no-sample
score-compose generate score*.yaml
```
> feat: added init --no-sample to disable default score generation

- .dockerignore
- .github/workflows/release.yaml
- Dockerfile
- internal/compose/convert_test.go
This PR is some ops/build work to optimise the dockerfile, validate it during CI, and pushing it to github packages on release.
> feat: auto build and publish docker image for g1.22

- internal/command/generate_test.go
- internal/compose/convert.go
> fix(convert): fix missing annotations on state load

- go.mod
- go.sum
- internal/command/generate_examples_test.go
- internal/command/init.go
- internal/command/init_test.go
- internal/compose/convert_test.go
- internal/project/project.go
- internal/provisioners/core_test.go
Pick up the fixes in https://github.com/score-spec/score-go/releases/tag/v1.7.1
> fix(framework): update score-go

- .github/workflows/release.yaml
Release is blocked due to version change.
> fix(ci): swap deprecated field

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
> Split CI versus release

- .github/workflows/ci.yaml
> Update ci.yaml - `docker run`

- .github/workflows/release.yaml
Update release.yaml - push container image's `latest` tag too
> Update release.yaml - push container image's `latest` tag too

- .goreleaser.yaml
> updated the goreleaser by removing deprecation

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
Update release.yaml - `cosign sign`.
I tested with a temporary test (not existing anymore) and after this PR will be merged into `main`, with the next releases users will be able to do:
```bash
cosign verify ghcr.io/score-spec/score-compose:0.20.0 \
--certificate-oidc-issuer=https://token.actions.githubusercontent.com \
--certificate-identity https://github.com/score-spec/score-compose/.github/workflows/ci.yaml@refs/pull/205/merge \
| jq .
```
And getting:
```
Verification for ghcr.io/score-spec/score-compose:0.20.0 --
The following checks were performed on each of these signatures:
- The cosign claims were validated
- Existence of the claims in the transparency log was verified offline
- The code-signing certificate was verified using trusted certificate authority certificates
[
{ …
```
> Sign container image with Sigstore cosign

- .github/workflows/release.yaml
Update release.yaml - Fix write release
> Update release.yaml - Fix write release

- .goreleaser.yaml
Update .goreleaser.yaml - cosign
> Update .goreleaser.yaml - cosign

- .github/workflows/release.yaml
Update release.yaml - Fix install cosign
> Update release.yaml - Fix install cosign

- .goreleaser.yaml
Update .goreleaser.yaml - Fix file names
> Update .goreleaser.yaml - Fix file names

- .github/workflows/ci.yaml
- README.md
Update ci.yaml - CI on main too
Like done with `score-k8s`:
- https://github.com/score-spec/score-k8s/pull/86
- https://github.com/score-spec/score-k8s/pull/85
> Update ci.yaml - CI on main too

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .github/workflows/scorecard.yml
In order to tackle the `Pinned-Dependencies` issues there https://github.com/score-spec/score-compose/security/code-scanning.
> digests for GHA actions

- Dockerfile
- https://github.com/score-spec/score-compose/security/code-scanning/15
- https://github.com/score-spec/score-compose/security/code-scanning/14
> Update Dockerfile - pinned digest for base container images

- README.md
Update README.md - Reorganize badges
> Update README.md - Reorganize badges

- .github/dependabot.yml
Fix https://github.com/score-spec/score-compose/pull/248
> Update dependabot.yml - Fix groups

- internal/command/default.provisioners.yaml
Update default.provisioners.yaml - update doc for the output of `score-compose provisioners list`.
> Update default.provisioners.yaml - update docs
