Dockerfile

this is adding missing dependencies in the alpine image to run the go binary.
https://stackoverflow.com/questions/36279253/go-compiled-binary-wont-run-in-an-alpine-docker-container-on-ubuntu-host

go dependencies in alpine

---

README.md
e2e-tests/resources/outputs/example-03-dependencies-service-a-output.txt
examples/03-dependencies/README.md
examples/03-dependencies/compose.yaml
examples/03-dependencies/service-a.yaml
internal/compose/convert.go
internal/compose/convert_test.go

Signed-off-by: Eugene Yarshevich <yarshevich@gmail.com>
The latest Score spec renamed previously introduced `workload` resource type into `service` to support a proper level of abstraction.
We also remove service dependencies enforcement (`depends_on` section) from the produced `compose.yaml` file, as this configuration is environment-specific.

Rename `workload` resource type into `service`

---

README.md
e2e-tests/resources/outputs/run --help-output.txt
e2e-tests/resources/outputs/run --verbose-output.txt
e2e-tests/resources/outputs/run -f example-score.yaml -p containers.hello.image=hello:1.1-output.txt
e2e-tests/resources/outputs/run-output.txt
e2e-tests/score-compose-cli.robot
e2e-tests/utility/generate-expected-outputs.py
go.mod
go.sum
internal/command/run.go

Properties overrides via command line parameters
Allows users to override individual properties via command line arguments.
For example:
```
score-compose run -f example-score.yaml -p containers.hello.image=hello:1.1
score-compose run -f example-score.yaml -p metadata.some-property=
```

Properties overrides via command line parameters

---

e2e-tests/resources/outputs/example-02-environment-output.txt
e2e-tests/resources/outputs/example-03-dependencies-service-a-output.txt
e2e-tests/resources/outputs/example-03-dependencies-service-b-output.txt
e2e-tests/resources/score-compose-shared.resource
examples/02-environment/README.md
examples/02-environment/score.yaml
examples/03-dependencies/README.md
examples/03-dependencies/service-a.yaml
examples/03-dependencies/service-b.yaml
go.mod
go.sum
internal/compose/convert.go
internal/compose/convert_test.go
internal/compose/templates.go
internal/compose/templates_test.go

We are planning to deprecate resource properties in the Score spec: https://github.com/score-spec/spec/issues/61
It removes resource properties from the example score.yaml files we store in this repo

removed properties from score spec

---

internal/compose/templates.go
internal/compose/templates_test.go

Fix to pass through strings without brackets, e.g. `$abc` -> `$abc`.

Fix: Do not substitute strings without brackets

---

go.mod
go.sum

Added missing `host` and `schema` properties for `httGet` probe spec.

fix: added missing host and schema properties for httGet probe spec

---

compose.yaml
e2e-tests/resources/outputs/example-01-hello-output.txt
e2e-tests/resources/outputs/example-02-environment-output.txt
e2e-tests/resources/outputs/example-03-dependencies-service-a-output.txt
e2e-tests/resources/outputs/example-03-dependencies-service-b-output.txt
e2e-tests/resources/outputs/example-04-extras-output.txt
e2e-tests/resources/outputs/run -f example-score.yaml --build test-output.txt
e2e-tests/resources/outputs/run -f example-score.yaml --overrides overrides.yaml-output.txt
e2e-tests/resources/outputs/run -f example-score.yaml -p containers.hello.image=hello:1.1-output.txt
e2e-tests/resources/outputs/run -f example-score.yaml-output.txt
e2e-tests/resources/overrides.yaml
examples/03-dependencies/README.md
examples/03-dependencies/compose.yaml
internal/command/run.go
internal/compose/convert.go
internal/compose/convert_test.go
score.yaml

This PR improves score-compose by allowing it to support multiple containers in the workload and still support published ports and services.
For example, running an api server and a backend worker in the same workload:
```
metadata:
name: my-project
service:
ports:
api:
port: 80
targetPort: 8080
containers:
api:
image: my-project/my-image:0.0.1
args: ["api"]
worker:
image: my-project/my-image:0.0.1
args: ["worker"]
```
This produces a compose file that looks like:
```
services:
my-project-api:
command:
- api
image: my-project/my-image:0.0.1
ports:
- target: 8080
published: "80"
my-project-worker:
command:
- worker
image: my-project/my-image:0.0.1
network_mode: service:my-project-api
```
Note that the services have a container name appended, the ports are only …

feat: added support for multiple containers in the same workload

---

go.mod
go.sum
internal/compose/convert.go
internal/compose/convert_test.go
internal/compose/templates_test.go

This PR brings in a fix from the score-go library: https://github.com/score-spec/score-go/pull/25
This means we still have access to extended metadata fields in the workload spec, and workload resource. 
The impact of this is low in this library, because other metadata fields were being ignored and not used anyway, however this keeps us up to date tracking the head of the library for any future changes.

fix: update score-go library to fix metadata fields

---

README.md
cmd/score-compose/main.go
e2e-tests/resources/outputs/run --help-output.txt
e2e-tests/resources/outputs/run --verbose-output.txt
e2e-tests/resources/outputs/run-output.txt
e2e-tests/resources/outputs/unknown-output.txt
internal/command/root.go
internal/command/run.go
internal/command/run_test.go

This PR fixes #30 and prevents the double printing of errors along with usage messages that aren't appropriate.
The sample giving in #30 now prints just the single error without usage string:
```
$ score-compose run -f ./score.yaml -o ./compose.yaml
Error: validating workload spec: jsonschema: '/containers/hello/command' does not validate with https://score.dev/schemas/score#/properties/containers/additionalProperties/$ref/properties/command/type: expected array, but got string
```

fix: remove double printing of errors and supress usage text when errors are present after parsing

---

e2e-tests/resources/outputs/example-04-extras-output.txt
go.mod
go.sum
internal/command/run.go
internal/command/run_test.go
internal/compose/convert.go
internal/compose/convert_test.go

This upgrades score-compose to score-go 1.1.0 (https://github.com/score-spec/score-go/releases/tag/v1.1.0). The only real change affecting score compose is some fixes to the service protocol strings and the fixed naming of volume read only. The old form of read_only will continue to work due to the call to `ApplyCommonUpgradeTransforms`. 
The example files and tutorials have been updated in score docs.
We also start adding CLI unit tests that are hopefully more easy to run than the robot e2e tests.

feat: upgraded score-go to 1.1.0 and call upgrade function

---

compose.yaml
internal/command/run.go
internal/command/run_test.go
internal/compose/convert.go
internal/logging/logging.go

Users face a log of confusion when features in the score file are ignored without any notice or error.
In this PR we do things to improve this:
1. Update the logger to the modern log/slog package which allows log levels to be tracked. We use a simple handler here that ignores structured fields and just writes out the message with the level. We don't need timestamps here since the execution of the problem is fast and deterministic at this time.
2. Reject the files element which isn't supported yet.
3. Log warnings for unsupported resources when falling back to the environment variable references.
4. Log warnings for the ignored spec sections: probes and resources.
For example we get the following output out of the big RunExample test:
```
$ ./score-compose run -f …
```

fix: reject unsupported features and log ignored ones

---

README.md
internal/command/init.go
internal/command/init_test.go
internal/command/root_test.go
internal/project/project.go

The init subcommand makes it easier to get started with Score compose!
```
$ score-compose init --help
The init subcommand will prepare the current directory for working with score-compose and prepare any local
files or configuration needed to be successful.
A directory named .score-compose will be created if it doesn't exist. This file stores local state and generally should
not be checked into source control. Add it to your .gitignore file if you use Git as version control.
The project name will be used as a Docker compose project name when the final compose files are written. This name
acts as a namespace when multiple score files and containers are used.
Usage:
score-compose init [flags]
Examples:
score-compose init --file score2.yaml
score-compose init --project score-compose2
Flags: …
```

feat: support score-compose init subcommand

---

internal/command/run_test.go
internal/compose/convert_test.go
internal/compose/envvar_tracker.go
internal/compose/templates_test.go

This PR makes it clear that the resource output properties used in placeholders are expected to be set and not optional. The compose spec expects resources to be provisioned and that failures in resource provisioning should prevent the workloads from being deployed. The analogue of this in Docker compose is that the expected resource references are not set. 
NOTE: that this doesn't necessarily apply to the `environment` resource type, whos outputs should be real outputs of the system environment where defaulting to an empty string is expected behavior.
So `${resources.db.user}` would require `$DB_USER` to be set, but `${resources.env.foo}` would allow `$FOO` to default to empty string.

fix: require env var substitutions to be set

---

internal/command/init.go
internal/command/init_test.go
internal/command/run.go
internal/compose/convert.go
internal/compose/convert_test.go
internal/compose/templates.go
internal/compose/templates_test.go
internal/project/project.go
internal/project/resource_uid.go
internal/project/state.go
internal/project/state_test.go

This PR lays the ground work for the upcoming `score-compose generate` command which provides more formal resource provisioning.
In this PR we establish a state tree that contains final workload specs and the states of all provisioned resources. 
The flow works in the following steps:
1. load state from disk or construct new state in memory (this is what run does here)
2. add any new or updated score workloads into the state
3. "prime" resources. This generates initial resource states for all resources that haven't been provisioned before, it also updates metadata and params, and ensures that there are no conflicting definitions. Note: it does not remove old resources that are no longer declared in workloads.
4. ~"provision" resources and~ set outputs. We have not implemented any …

feat: added resource state model, priming, and legacy output generation

---

internal/command/generate.go
internal/command/generate_test.go
internal/command/run.go
internal/compose/convert.go
internal/compose/convert_test.go
internal/project/state.go
internal/project/state_test.go

Depends on https://github.com/score-spec/score-compose/pull/65
This PR adds the `--image` and `--build` flags to score-compose `generate`.
The `--image` flag works like other score implementations, and provides a default image for any containers that have `image: .`. If you want to override a container which already has an image, use `--override-property` instead.
The `--build` flag accepts either a plain directory string as a build context per container: `--build hello-world=./subdir`, or a more complex json structure which supports additional context things like args and custom docker files: `--build 'hello-world={"dockerfile":"Dockerfile.example"}'`.
Both `--image` and `--build` are stored in the context so that any future generate calls continue to use them unless the workload is …

feat: support --image and --build on score-compose generate 

---

internal/command/default.provisioners.yaml
internal/command/generate.go
internal/command/generate_test.go

When resource provisioners create services that take some time to start up or have init containers that _must_ complete before the workload services start, we need to determine a start up order.
This PR adds a new service called `wait_for_resources` which is used as a coordination point. This is only added when resource services are provisioned and it gets a dependency added for each one. When present, the workload services will now wait for this service to run before they may start.
You can see this affect in the unit test added in generate_test.go.
The ready condition is tuned based on what we can detect about the container. Since we cannot always distinguish services that are init containers, we have an opt-in / best-effort label which can be added in provisioners to indicate that we …

feat: support dependency order between resource services and workload services

---

internal/command/generate.go
internal/command/generate_test.go
internal/command/run.go
internal/command/run_test.go
internal/compose/convert.go
internal/compose/convert_test.go

Until now, score-compose has not supported container files. This is a big lack of a fairly core feature of the score specification. Now we have it!
Given a score file like:
```
metadata:
name: example
service:
ports:
www:
port: 8080
targetPort: 80
containers:
example:
image: nginx:latest
files:
- source: ./1084-536x354-grayscale.jpg
noExpand: true
target: /usr/share/nginx/html/1084-536x354-grayscale.jpg
- target: /usr/share/nginx/html/index.html
content: |
<html>
<h1>Hello! I am workload '${metadata.name}'</h1>
</html>
```
We now get a useful nginx server out of it:
This is great when you're deploying an app which uses a container image that you don't control.

feat: added support for container files

---

README.md
examples/06-resource-provisioning/README.md
internal/provisioners/cmdprov/commandprov.go
internal/provisioners/cmdprov/commandprov_test.go
internal/provisioners/loader/load.go

This PR add's a new kind of provisioner: `cmd`. This allows you to encode the provisioner inputs as json and pass them via stdin to a new process, this process will execute and pass json back out to the resource system to persist.
This supports:
- `cmd://my-binary` - a binary that exists on the `$PATH`
- `cmd:///an/absolute/path` - an absolute path
- `cmd://./a/relative/path` - a relative path
- `cmd://~/bin/thing` - something in the home directory
Additional arguments can be passed by providing them in the `args` configuration:
```
- uri: cmd://python3
type: my-resource-type
args:
- -c
- |
import sys, json
inputs = json.load(sys.stdin)
print(json.dumps({"resource_outputs": {"key": "value"}})
```
And stderr content will be printed in the same shell as the `score-compose generate` …

feat: added support for cmd:// provisioners

---

README.md
go.mod
go.sum
internal/command/default.provisioners.yaml
internal/command/generate_test.go

See demo video here in Loom https://www.loom.com/share/f51c30a60e38477fa7dbf1b83e316c42?sid=19960a22-0197-4e5a-8370-3700d1d95f97.
This gives an S3 compatible resource that can be used to build applications talking to object stores. Since the S3 API is generally a universal standard now, this is a great API use when building apps that needs some object storage.
The outputs are `endpoint`, `bucket`, `access_key_id` and `secret_key` which are the standard outputs.
This will be documented in the combined docs push for project Melody.

feat: added minio-based s3 provisioner

---

README.md
examples/02-environment/README.md
internal/command/generate.go
internal/command/generate_test.go

This PR adds a backwards compatibility feature to generate that was present in the existing run command.
Now you can specify `--env-file` to output a compose-style environment file that can be filled in with relevant values.
It's recommended to check this into the repo along with the score file so that developers know what to provide here.
eg: with a score file like:
```
metadata:
name: hello-world
containers:
hello:
image: busybox
variables:
LOG_LEVEL: ${resources.env.LOG_LEVEL}
STAGE: ${resources.env.STAGE}
resources:
env:
type: environment
```
Running with `--env-file .env` will output:
```
LOG_LEVEL=
STAGE=
```
These should both be filled in appropriately before running `docker compose up`

feat: support for --env-file on generate

---

examples/02-environment/README.md
examples/06-resource-provisioning/README.md
internal/command/generate_test.go
internal/project/substitution.go
internal/project/substitution_test.go

This PR expands the set of supported characters inside a `${..}` placeholder and makes the templating system more predictable and reliable.
In the past a placeholder like `${x y z}` would just be returned as `${x y z}` without any error or modification. Now we will steer users towards escaping it instead if this is the desired behavior: `$${x y z}`.
As a side effect this fixes #91 as it now allows the forward slash inside the placeholder.

feat: support /-separated annotation keys in metadata reference

---

examples/03-files/README.md
internal/command/generate.go
internal/command/generate_test.go
internal/compose/convert.go
internal/compose/convert_test.go

The score specification intends that the container file elements that have a source path are resolved relative to the source of the score file and not just relative to the working directory. This ensures that `score-compose generate sub-component/score.yaml` works as expected.
This PR fixes this by tracking the source file info in the state object and using this when resolving the source file.

fix: resolve file source relative to the score file

---

examples/09-dns-and-route/README.md
examples/09-dns-and-route/score.yaml
internal/command/default.provisioners.yaml
internal/command/generate_examples_test.go
internal/command/generate_test.go
internal/project/state.go
internal/provisioners/core.go
internal/provisioners/core_test.go

This PR adds initial basic provisioner support for the dns and route resource types following the same patterns already established by score-humanitec and similar implementations.
The dns provisioner implementation is intentionally simple: it just outputs `host=localhost`. More advanced implementations can do more clever things like generating random names, setting up a dns resolver, or modifying /etc/hosts.
The route resource sets up an nginx service published on port 8080 with host+path routing to the desired workload services.
Fixes #85

feat(provisioners): added dns.default and route.default provisioners

---

README.md
examples/08-service-port-resource/README.md
examples/08-service-port-resource/score.yaml
examples/08-service-port-resource/scoreA.yaml
examples/08-service-port-resource/scoreB.yaml
internal/command/default.provisioners.yaml
internal/command/generate_examples_test.go

The `service-port` resource type allows a workload to reference a service port exposed by another workload.
**NOTE**: this is similar to the `service` resource type from score-humanitec, but has a slightly different contract since it targets a specific port. We will consider implementing service-port in humanitec in the future.
For example, if workload-b exposes a "web" port with port 80 -> targetPort 8080, this service resource will resolve to the docker compose service name of the workload and the target port on the network interface to call for the "web" port. 
Another implementation such as score-helm, might convert this into the particular cluster-ip service provisioned for that service port and return it's name and port 80.
Appropriate errors are thrown if the required workload …

feat: support service-port.default resource provisioner

---

go.mod
go.sum
internal/compose/convert.go
internal/compose/convert_test.go

There was previously a special case in score-go for converting 2 part placeholders like `${resources.foo}` into just "foo". This was a legacy behavior due to the way volumes are linked into containers. However this was a behavior only needed by score-compose and incompatible with other score implementations. So in 1.5.1 of score-go we removed the special casing and now throw the original error and move the handling of this field specifically into the volume field substitution in score-compose. This means we restrict this special casing into only the particular field and resource type combination that need it 👍 
Going forwards the `${resources.foo}` placeholder will throw an error in most cases because it expects an output lookup key. Certain resources implemented by …

fix: upgrade score-go and move special 2-part volume placeholder impl

---

go.mod
go.sum

Routine score-go update for https://github.com/score-spec/score-go/releases/tag/v1.5.2.

fix: upgrade score-go framework to pick up bug fix on resource param comparisons

---

examples/09-dns-and-route/README.md
internal/command/default.provisioners.yaml
internal/command/generate_test.go

The existing route provisioner was inconsistent in behavior and was doing Prefix matching on non-/ routes by default, not providing any Prefix matching on the / route, and not supporting any control mechanisms either way.
This PR fixes this so that we can do:
```
metadata:
name: example
containers:
web:
image: ealen/echo-server:0.9.2
service:
ports:
web:
port: 8080
targetPort: 80
resources:
dns:
type: dns
route2:
type: route
params:
host: ${resources.dns.host}
port: web
path: /first
route3:
type: route
metadata:
annotations:
score-compose.score.dev/route-provisioner-path-type: Exact
params:
host: ${resources.dns.host}
port: web
path: /second
```
And using curl we can see that:
- `curl http://localhost:8080/| jq .http.originalUrl` -> 404
- `curl …

fix(route-provisioner): support Prefix vs Exact routing

---

internal/command/default.provisioners.yaml

While testing this with a new service I found that the generated user doesn't have access to the public schema in the postgres database.
This PR adds the misisng lines during setup.

fix: add public schema grant to postgres resource provisioner

---

examples/09-dns-and-route/README.md
examples/09-dns-and-route/score.yaml
internal/command/default.provisioners.yaml
internal/command/generate_test.go

I made a mistake in the initial implementation of the route provisioner. I had written it so that it removed the matched path (and it also didn't work at all with regex routes).
After looking at the general assumptions of the Humanitec score docs and existing route provisioners in Humanitec I can see that the expectation is actually that this is a route match that supports regex and simply proxies the request without rewriting the path.
Naturally, users are _welcome_ to add a custom provisioner that does this slightly differently, but the basic case should be to support patterns and regex like this:
```
resources:
animals-route:
type: route
params:
host: api.example.com
path: /projects/[^/]+/animals
port: 8080
fruit-route:
type: route
params:
host: api.example.com
path: …
```

fix: remove path rewrite from route provisioner

---

examples/04-multiple-workloads/README.md
examples/09-dns-and-route/README.md
examples/09-dns-and-route/score.yaml
internal/command/default.provisioners.yaml

In the initial implementation of the dns provisioner, we limited it to generated localhost domains because any other domains may not resolve to the loopback address. We detailed this as a limitation.
However we've recently found that almost all systems today respect https://datatracker.ietf.org/doc/html/rfc6761#section-6.3 which allows *.localhost to resolve to the loopback addresses!
So in this PR we upgrade the dns provisioner and the docs for the routing example so that we can generate a hostname that looks like `dns<random 6>.localhost`.
This allows us to more easily have 2 different score workloads in the same project with different routing. 
Think of an API and an APP (UI) together which would be a common use case.

feat: support random dns names via rfc6761-6.3

---

README.md
examples/10-amqp-rabbitmq/README.md
examples/10-amqp-rabbitmq/score.yaml
internal/command/default.provisioners.yaml
internal/command/generate_examples_test.go

We have a usecase for a rabbitmq provisioner to generate a stateful message broker.
This PR adds it :)
When I run the example project I can see:
```
INFO: Writing new state directory '.score-compose'
INFO: Writing new state directory '.score-compose' with project name '10-amqp-rabbitmq'
INFO: Writing default provisioners yaml file '99-default.provisioners.yaml'
INFO: Found existing Score file './score.yaml'
INFO: Read more about the Score specification at https://docs.score.dev/docs/
INFO: Loaded state directory with docker compose project '10-amqp-rabbitmq'
INFO: Validated workload 'hello-world'
INFO: Successfully loaded 8 resource provisioners
INFO: Provisioned 2 resources
INFO: Converting workload 'hello-world' to Docker compose
```
```
[+] Running 4/6
⠧ Network …
```

feat: added rabbitmq/amqp provisioner

---

README.md
examples/06-resource-provisioning/README.md
go.mod
go.sum
internal/command/resources.go
internal/command/resources_test.go
internal/command/root_test.go
internal/command/run_test.go

This PR adds the `resources list` and `resources get-outputs` subcommands to score-compose.
This make it much easier to connect post-generate steps to the compose project. For example:
- extracting the generated dns name for making requests to an ingress route
- extracing the database usernamd and password to access it from a test container
etc.
This also includes some related documentation improvements.
3 output formats are supported: raw json (the default), yaml (better for humans), and Go template which allows for extracting particular values or combinations of values when the environment does not have access to tools like `jq` or `yq` or wants to extract multiple values in one shot for example `--format 'amqp://{{ .username }}:{{ .password }}@{{ .host }}:{{ .port }}/{{ .vhost }}'`

feat: added resources subcommands

---

examples/01-hello/README.md
examples/02-environment/README.md
examples/04-multiple-workloads/README.md
examples/08-service-port-resource/README.md
internal/command/generate_examples_test.go
internal/command/generate_test.go
internal/command/init_test.go
internal/command/run_test.go
internal/compose/convert.go
internal/compose/convert_test.go
internal/provisioners/core.go
internal/provisioners/core_test.go

@mathieu-benoit and I were trying to get a Score adaption of https://github.com/Azure-Samples/aks-store-demo/tree/main working with score-compose but found that a routing configuration assumed that the hostname was equal to the workload name. However score compose was using (workload name)-(1st container name) because it shares the network of the 1st container.
This PR fixes this by setting the hostname directly on the 1st container as appropriate. 
This shouldn't break compatibility and should make things more readable when workloads only contain one container.

fix: set workload network hostname to workload name

---

README.md
examples/05-volume-mounts/README.md
internal/command/default.provisioners.yaml
internal/command/generate_test.go
internal/command/init.go
internal/command/init_test.go
internal/command/resources_test.go
internal/compose/convert.go
internal/compose/convert_test.go

This PR changes the way that volumes are provisioned in score-compose. Previously volumes HAD TO be type=volume and return a source value, and were limited to just being persistent docker compose volumes.
This PR now removes the restriction on the type field and just requires that the outputs must match one of the 3 kinds of supported docker compose volume mounts: tmpfs, bind, or persistent volume - and we also support the extended attributes https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
This also modifies the way the 2-part resource-id placeholder is resolved. `${resources.foo}` will not resolve to `type.class#workload.foo` (the resource uid).

fix: assert volume based on outputs and not type

---

README.md
examples/11-mongodb-document-database/README.md
examples/11-mongodb-document-database/score.yaml
internal/command/default.provisioners.yaml
internal/command/generate_examples_test.go
internal/command/generate_test.go

We have datastore implementations for postgres and redis, and this PR introduces a new provisioner for a document DB: mongodb.
This provisions a single mongo container with persistent data and healthcheck. An exec command is provided to support working with the data.
generate:
```
$ score-compose generate score.yaml
INFO: Loaded state directory with docker compose project '11-mongodb-document-database'
INFO: Validated workload 'hello-world'
INFO: Successfully loaded 9 resource provisioners
INFO: mongodb.default#hello-world.db: To connect to mongo: "docker exec -ti 11-mongodb-document-database-mongo-JTyNG0-1 mongosh -u user-HCEtQlbs -p XtCgk7PWMqpORIsn"
INFO: Provisioned 1 resources
INFO: Converting workload 'hello-world' to Docker compose
```
And docker compose up returns:
```
[+] Running …
```

feat(provisioners): added mongodb default provisioner

---

.github/workflows/release.yaml

Release 0.14.0 failed due to missing permissions.

fix: re-add contents:write permissions to release ci

---

README.md
internal/command/generate.go
internal/command/generate_test.go

See #130. This corrects the parsing of the `--build` json by using the compose yaml/json loader which pulls in all the extra unmarshalling magic for dynamic types that the json reader cannot cope with.
A test is added to check that this works as expected.
As a side effect, this also supports inline yaml.

fix(generate): correct parsing of --build json

---

examples/01-hello/README.md
examples/01-hello/score.yaml
examples/02-environment/README.md
examples/04-multiple-workloads/README.md
examples/08-service-port-resource/README.md
internal/command/generate_examples_test.go
internal/command/generate_test.go
internal/command/init_test.go
internal/command/run_test.go
internal/compose/convert.go
internal/compose/convert_test.go

This allows annotations to be used during post processing, and this also follows the general behavior of other score implementations.
For example injecting dapr sidecars:
```
yq '(.services) += (.services | 
with_entries(select((.value | has("hostname")) and (.value.annotations | has("dapr.io/enabled")))) | 
with_entries(. as $e | .key |= . + "-sidecar"| .value |= {"image": "daprio/daprd:latest", "command": ["./daprd","--app-id", ($e.value.annotations."dapr.io/app-id" | "unknown")], "network_mode": "service:" + $e.key}))' examples/01-hello/compose.yaml
```
This would support score workloads with the dapr enabled annotation.
```
metadata:
name: foo
annotations:
dapr.io/enabled: "true"
dapr.io/app-id: "foo-app"
...
```
🎸

feat: pass through workload metadata.annotations onto services

---

examples/09-dns-and-route/README.md
internal/command/default.provisioners.yaml
internal/command/generate_test.go

Increased the max client body size default from 1m to 10m. It's too easy these days to hit the max. Also added support for nginx config snippets just like the Kubernetes ingress does.

feat(route-provisioner): increased client body size and added nginx snippet annotations

---

internal/command/generate.go

Missing a fmt.Sprintf.
Fixes #138

fix: unformatted image override message

---

README.md
examples/13-kafka-topic/README.md
examples/13-kafka-topic/score.yaml
internal/command/default.provisioners.yaml
internal/command/generate_examples_test.go

See the newly added example in examples/13-kafka-topic. This provisions a 3-partition kafka topic on a random host.
```
$ go run ../../cmd/score-compose resources list
dns.default#hello-world.dns
kafka-topic.default#hello-world.bus
route.default#hello-world.route
$ go run ../../cmd/score-compose resources get-outputs 'kafka-topic.default#hello-world.bus'
{"host":"kafka-e9KQfd","name":"topic-lTppsn","num_partitions":3,"port":"9092"}
```
You can see in the example screenshot that the redpanda console can connect to it successfully:
Fixes #149

feat: added kafka-topic provisioner

---

README.md
internal/command/root_test.go
internal/command/run.go
internal/command/run_test.go

The run command is still accessible  and can still be used in CI if needed, but it is not removed from the documented behavior.

feat: hide deprecated run command

---

.github/workflows/release.yaml

Another attempt at fixing the goreleaser command, this time following what's in the docs.
Trial and error.

chore(ci): fix goreleaser

---

README.md

As discussed here https://github.com/score-spec/score-k8s/pull/17#discussion_r1657401676 do we want to link to the main spec for information on how to get in touch rather than duplicating the information here.

Updated get in touch section with correct reference

---

internal/command/resources.go
internal/command/resources_test.go

See #160.
Ensure there's a newline so that output in a terminal makes sense and doesn't mess up printing.

fix: ensure resource output template has a newline

---

internal/command/check_version.go
internal/command/check_version_test.go
internal/command/root_test.go
internal/version/version.go
internal/version/version_test.go

With the ongoing development of score-compose, new features and provisioners come and go. Often project makefiles or CI pipelines need to check that the installed version provides specific features that are relatively new. Other than this, there is no particular drive to update the score-compose binary on a system.
This PR, adds a `check-version` subcommand that can be used to quick quick without regex or anything too weird that the version is the one expected.
It supports partial semver as well as `=`, `>=`, and `>` constriants.

feat: added check-version subcommand

---

internal/command/generate.go
internal/command/generate_test.go

I found an interesting condition with the wait-for-resources service when doing a command like `docker compose up <some-service> --wait`:
```
$ docker compose up hello-world-first --wait
[+] Running 3/3
✔ Container 12-mysql-database-mysql-8MjJEo-1        Healthy                                                                                                                                                                                                                    0.0s 
✔ Container 12-mysql-database-wait-for-resources-1  Created                                                                                                                                                                                                                    0.0s 
✔ Container …
```

fix: improve depends-on condition for wait-for-resources

---

internal/command/default.provisioners.yaml

I noticed while working with the rabbitmq provisioner that sometimes the container errors while waiting for the service to come up. This is usually when the system is constrained by some other load like a video call.
When looking at the logs of the process I can see that it's not ready by the time the healthcheck gives up and this problem can be resolved by increasing the timeouts. I've done this in this PR to increase most services up to approximately 30s of retry attempts.

fix: increase healthcheck retries

---

README.md
examples/06-resource-provisioning/README.md
examples/08-service-port-resource/README.md
internal/command/generate.go
internal/command/generate_examples_test.go
internal/command/generate_test.go

This removes the need for some of the weird workarounds used in local development to publish private ports from workloads or resources that are usually only exposed to services within the docker network.
Now to access a workload port that doesn't have a dns+route to expose it, you can now use `--publish <host port>:<workload name>:<container port>` to add a port publish to the output compose.yaml file. This does not require that the port is set as a Score service port, therefore this can be used for things like debugging ports. For example, `--publish 8080:my-workload:80` would publish a HTTP port to port 8080.
Now to access a resource port like a postgres, rabbitmq, or other resource that wouldn't be published externally you can use `--publish <host port>:<resource uid>.output:<container …

feat(generate): added --publish port CLI flag

---

internal/command/generate.go
internal/command/generate_test.go

See #173. The initial request was to support this with a workload name clarifier but after discussion we decided that we want to push folks away from a "mega command" and towards a more iteration-based approach. So when users hit this error, they should break their command into separate invocations.

fix: added validation error when --image or --build are used with multiple score files

---

README.md
examples/06-resource-provisioning/README.md
go.mod
go.sum
internal/command/init.go
internal/command/init_test.go
internal/provisioners/loader/load.go

Installing provisioners by copying yaml files around is not a great UX and makes things unecessarily multi-step.
This PR improves this by adding a `--provisioners <URI>` flag which downloads a provisioner file using either http, git, or local filesystems and adds it into the .score-compose state directory at the top of the stack.

feat: support validating and installing provisioner files by uri

---

internal/command/default.provisioners.yaml

Update default.provisioners.yaml - `postgres:17-alpine` (aligned with https://github.com/score-spec/score-k8s/pull/38) and `mongo:8`

Update default.provisioners.yaml - `postgres:17` and `mongo:8`

---

.github/dependabot.yml
.github/workflows/release.yaml

Create `dependabot.yml` to automate the process of upgrading go, Docker and GHA actions versions.
Also took the opportunity to avoid the double run of the CI in a PR, so now CI (`release`) is triggered either on PR or in a push on `main`.

Create `dependabot.yml` and fix CI for push on main OR pull_request

---

go.mod
go.sum

Fixing https://github.com/score-spec/score-compose/issues/188 by running `go mod edit -replace github.com/imdario/mergo=dario.cat/mergo@v1.0.0`.
I then was able to successfully run:
```
go mod tidy
go get -u all
```

Fix `imdario/mergo` version

---

.github/workflows/ci.yaml

Added a  `go vet ./..` for reporting suspicious constructs that might indicate errors ...
it updates the `ci.yml` and adds a new test called **Run Go Vet**

Added a go vet for consistency

---

internal/command/init.go
internal/command/init_test.go

This PR add the oci example to `init.go` and also a updated output format. #178 
By adding the oci example it help people to understand the new feat.

Added oci example in `score-compose init --help`

---

internal/command/init_test.go

**Fixed the main_init_test.go**
The following `TestInitWithProvisioners` often fails , so by adding this new lines will help to check whether the expected provisioner URI is present in the `provs` collection of provisions or not..

Fixed the init_test

---

internal/command/default.provisioners.yaml

Found these while testing compatibility between score-k8s and score-compose.
1. region for minio should be us-east-1. S3 clients using sigv4 signing may require a region.
2. simplify the bucket name to not have a . in it
3. improvement the startup scripts reliability with set-eu

fix(provisioners): small s3 reliability improvements

---

examples/02-environment/README.md
examples/02-environment/score.yaml
internal/command/generate_examples_test.go
internal/compose/convert.go
internal/compose/convert_test.go

This finishes off the last bit of work and fixes #148.
We need to use the custom unescaper to not escape the variables here. This allows it to match the expected runtime behavior.

fix: don't unescape dollars in environment variable placeholders

---

README.md
examples/15-mssql-database/README.md
examples/15-mssql-database/score.yaml
internal/command/default.provisioners.yaml

Add a defalult MSSQL provisioner
Fix #195 
```bash
~$ go run ../../cmd/score-compose/main.go init -f ./score.yaml 
INFO: Writing new state directory '.score-compose'
INFO: Writing new state directory '.score-compose' with project name '15-mssql-database'
INFO: Writing default provisioners yaml file 'zz-default.provisioners.yaml'
INFO: Found existing Score file './score.yaml'
$ go run ../../cmd/score-compose/main.go generate score.yaml 
INFO: Loaded state directory with docker compose project '15-mssql-database'
INFO: Validated workload 'example'
INFO: Successfully loaded 13 resource provisioners
INFO: mssql.default#example.db: mssql.default#example.db: To connect to mssql: "docker run -it --network 15-mssql-database_default --rm mcr.microsoft.com/mssql/server:latest mysql …
```

feat(default-provisioner): add mssql default provisioner support

---

go.mod
go.sum
internal/command/generate.go
internal/command/run.go

The mergo replace directive that used be necessary was still hanging around and preventing the user of `go run github.com/score-spec/score-compose/cmd/score-compose@0.24.0` when run inside a go module.
This PR fixes it now that `dario.cat/mergo` has the correct redirects in place.

fix: remove mergo replace directive

---

go.mod

As it says on the tin, update the binary go version. For some reason missed by dependabot.

chore: update go to 1.23.5

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
Dockerfile
internal/version/version.go

Fixing https://github.com/score-spec/score-compose/issues/268.
Not related to the regression between `0.24.2` and `0.25.0`, also fixing an issue that has been there for a long time with the container image with the `--version`:
```bash
score-compose 0.0.0 (build: 2025-01-21T17:02:05Z, sha: 974fdcebfa674487e9626a1a83951c07476b3273-dirty)
```
Knowing that the `goreleaser` config was already using this: https://github.com/score-spec/score-compose/blob/main/.goreleaser.yaml#L11.
_Note: Not related to this PR, but the container base image to build the final image (`distroless`) is now based on `alpine` in order to speed up the container build process._

Fix `--version`

---

internal/command/default.provisioners.yaml

Use `mirror.gcr.io/` to avoid DockerHub rate limits error while using default provisioners:
- https://docs.docker.com/docker-hub/usage/
- https://cloud.google.com/artifact-registry/docs/pull-cached-dockerhub-images
- https://devtron.ai/blog/dodging-docker-hub-rate-limits-the-ultimate-cheat-code-for-your-ci-cd-pipeline/
> Starting April 1, 2025, all users with a Pro, Team, or Business subscription will have unlimited Docker Hub pulls with fair use. Unauthenticated users and users with a free Personal account have the following pull limits:
> - Unauthenticated users: 10 pulls/hour
> - Authenticated users with a free account: 100 pulls/hour

Use `mirror.gcr.io/` to avoid DockerHub rate limits error while using default provisioners

---

internal/command/init.go
internal/command/init_test.go

**Add `--no-default-provisioner flag`**
Adds the ability to disable automatic creation of the default provisioners file (zz-default.provisioners.yaml) during score-compose init
#286

feat: add no-default-provisioners flag

---

internal/command/default.provisioners.yaml

A new provisioner, `postgres-instance`, has been added. It is similar to the `postgres` provisioner but differs in key aspects:
- Unlike the `postgres` provisioner, `postgres-instance` does not provide `database/name` as an output.
- It operates without shared resources (local )

Postgres-instance provisioner added

---

internal/command/default.provisioners.yaml

Update default.provisioners.yaml - `service-port` fail if not found

Update default.provisioners.yaml - `service-port` fail if not found

---

Makefile
examples/03-files/score.yaml
examples/05-volume-mounts/score.yaml
go.mod
go.sum
internal/command/generate_examples_test.go
internal/command/generate_test.go
internal/compose/convert.go
internal/compose/convert_test.go

github.com/score-spec/score-go v1.10.0
https://github.com/score-spec/score-go/pull/103 based on https://github.com/score-spec/spec/pull/123#issuecomment-2793203515
This PR also makes sure that previous/old `files|volumes` spec is still working while we support the new spec.
Both examples working with this new version:
Old `files|volumes` spec:
```yaml
metadata:
name: hello-world
containers:
hello:
image: .
files:
- target: /fileB.txt
content: |
I am ${metadata.name}
volumes:
- target: /data
source: ${resources.data}
resources:
data:
type: volume
```
New `files|volumes` spec:
```yaml
metadata:
name: hello-world
containers:
hello:
image: .
files:
"/fileB.txt":
content: |
I am ${metadata.name}
volumes:
"/data":
source: ${resources.data} …
```

Support new `files|volumes` spec with `score-go` `v1.10.0`

---

internal/command/generate_examples_test.go
internal/command/generate_test.go
internal/command/run_test.go
internal/compose/convert_test.go

In unit tests, fix `docker compose` `convert` by `config`, since https://github.com/docker/compose/releases/tag/v2.36.1, as per https://github.com/docker/compose/pull/12850.
Now, to run the unit tests locally, `docker compose version` should be greater or equal to `v2.36.1` in your local machine.

Unit tests: Fix `docker compose` `convert` by `config`

---

internal/command/default.provisioners.yaml

We use the RabbitMQ default provisioner regularly, and sometimes we get start up failures due to:
```
...                                                                                                                                                                 
✔ Container integration-tests-rabbitmq-2oSrWo-1       Healthy    
✘ Container integration-tests-rabbitmq-2oSrWo-init-1  service "rabbitmq-2oSrWo-init" didn't complete successfully: exit 64           
...                                                                                        
```
And looking that the logs shows
```
docker logs integration-tests-rabbitmq-2oSrWo-init-1
+ source /db-scripts/vhost-yoSrxqzL.sh
+ rabbitmqctl list_vhosts
+ grep vhost-yoSrxqzL
Error: unable to perform an operation on node …
```

fix(provisioners): wait for rabbitmq vhosts before init script
